image:
  repository: afsdigitalstudio-docker.jfrog.io/comet/react
  tag: latest
  # pullSecret:
  pullPolicy: Always

replicas: 2

port: 80

service:
  type: ClusterIP

ingress:
  enabled: true
  hostname: "react.dev.project-gsa.com"
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: cookie
  tls:
    - hosts:
      - "dev.project-gsa.com"
      - "*.dev.project-gsa.com"